export const NOTIFICATIONS_LOG_LIMIT = 40;
export const NOTIFICATIONS_MAX_ITEMS = 20;
export const NOTIFICATIONS_PATH_TRUNCATE_MAX = 28;
export const NOTIFICATIONS_SLOW_REQUEST_MS = 1000;
export const NOTIFICATIONS_TIMESTAMP_FORMAT = 'mm-dd, HH:MM';
